### ISSUE TITLE
按照教程搭建了，但是一直无法访问

### ISSUE THREAD

**Issue by MicroMatrixOrg** [AoEiuV020/Url-Shorten-Worker#9]
按照教程搭建了，但是一直无法访问，变量和kv变量都设置了。但是网页就是打不开

**Comment by crazypeace** [comment]
1. 网页打不开 你看到了什么 截图丢上来
 你的描述就像，打电话给汽车客服，我加了油，插了钥匙，但是汽车不动。
2. 试试这个教程
https://www.nodeseek.com/post-58723-1

**Comment by MicroMatrixOrg** [comment]
回复下，CF如果无法打开网页，那可能是被屏蔽了。建议自定义域名那里设置一个自己的域名来进行访问。这样就可以正常打开网页了。注意不是路由那里设置。
